### ISSUE TITLE
Sample Run

### ISSUE THREAD

**Issue by mattloose** [LooseLab/ROBIN#29]
Need to add in sample start from ROBIN.

Multiple steps needed.

```[tasklist]
### Tasks
- [ ] https://github.com/LooseLab/ROBIN/issues/31
- [x] https://github.com/LooseLab/ROBIN/issues/30
- [x] Select Position
- [x] Start run with correct basecalling configuration and analysis settings.
```
